version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 211125664698.dkr.ecr.ap-south-1.amazonaws.com
      - echo Pulling the latest image from ECR...
      - docker pull 211125664698.dkr.ecr.ap-south-1.amazonaws.com/superset-repo:latest
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t superset .
      - docker tag superset:latest 211125664698.dkr.ecr.ap-south-1.amazonaws.com/superset-repo:latest
  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      - docker push 211125664698.dkr.ecr.ap-south-1.amazonaws.com/superset-repo:latest
